version: 2.1

jobs:
  build_stg:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build project
          command: |
            npm install
            npm run build
            sudo apt install rsync
            rsync -avz --exclude '.git' -e "ssh -v -p 20022" ~/repo/docs $SSH_USER@$SSH_STAGE_HOST:/var/www/apps.urban.org/features/prioritize-funding/
workflows:
  version: 2
  build_stg:
    jobs:
      - build_stg:
          context:
            - apps
          filters:
            branches:
              only: add-circle
